### ISSUE TITLE
API info link?

### ISSUE THREAD

**Issue by dilgreen** [glowkeeper/mccs-alpha-api-ui#5]
Since this is - at the outset, at leat - a UI to test the APIs on MCCD, screens probably shouldn't come from a workflow / service design space initially - but be produced with reference to what the APIs offer. Where can I read these?

**Comment by glowkeeper** [comment]
I believe (hope) they are here:

[User](https://documenter.getpostman.com/view/10168004/SWTD7wqB?version=latest)

[Admin](https://documenter.getpostman.com/view/10168004/SzYYyy7e?version=latest)
