### ISSUE TITLE
Password in plain text

### ISSUE THREAD

**Issue by glowkeeper** [glowkeeper/mccs-alpha-api-ui#6]
The current sign up screen doesn't give the ability to obscure that which is typed

**Comment by glowkeeper** [comment]
Now it stars out the password as you type. Maybe need a show function?

**Comment by dilgreen** [comment]
Just made an account, pwd not obscured on sign-up screen.

Dil Green
[digital anthropology blog](http://www.digital-anthropology.me)
[Open Credit Network](http://opencredit.network)
@dilgreen on twitter and generally
Use this link to book a half hour slot with me!
https://calendly.com/dilgreen/30-min-video-call

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by glowkeeper** [comment]
> Just made an account, pwd not obscured on sign-up screen.

Fixed in the latest build - just need to ping Geoff and get him to integrate it into the server :)

**Comment by dilgreen** [comment]
Cool tx. I am thinking about 'design' stuff. Need to have a chat, all four of us, soon.

Dil Green
[digital anthropology blog](http://www.digital-anthropology.me)
[Open Credit Network](http://opencredit.network)
@dilgreen on twitter and generally
Use this link to book a half hour slot with me!
https://calendly.com/dilgreen/30-min-video-call

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by glowkeeper** [comment]
At some point, we may wish to have an option to view the password in plain text, but I'm going to close this for now
